SELECT DISTINCT
  ?artist as ?uri
  sql:BEST_LANGMATCH(?label, '%%lang%%', 'en') AS ?label
  ?birth
  ?death
  ?pic
WHERE {
  ?artist a ecrm:E21_Person ;
         rdfs:label ?label .
  OPTIONAL { ?artist foaf:depiction ?pic }
  OPTIONAL { ?artist schema:birthDate ?birth }
  OPTIONAL { ?artist schema:deathDate ?death }

  # involved at least in one activity
  ?activity ecrm:P14_carried_out_by ?artist .
}
GROUP BY ?artist ?pic ?birth ?death
ORDER BY desc(COUNT(?activity))
LIMIT %%lim%%
OFFSET %%offset%%
