PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?expression, SAMPLE(?title) AS ?title, SAMPLE (?composer) AS ?composer
FROM <http://data.doremus.org/>
FROM <http://data.doremus.org/vocabulary>

WHERE {
    <%%uri%%> a efrbroo:F22_Self-Contained_Expression ;
             mus:U12_has_genre ?genre .
    ?expCreationOrig efrbroo:R17_created <%%uri%%> ;
                ecrm:P9_consists_of ?activityOrig .
    ?activityOrig ecrm:P14_carried_out_by ?personOrig .
    ?personOrig ecrm:P1_is_identified_by ?composer .


    ?expression a  efrbroo:F22_Self-Contained_Expression ;
            ecrm:P102_has_title ?title .
    ?expCreation efrbroo:R17_created ?expression ;
                ecrm:P9_consists_of ?activity .
    ?activity ecrm:P14_carried_out_by ?person .
    ?person ecrm:P1_is_identified_by ?composer .
    FILTER (str(?title) != "")
}
GROUP BY ?expression
LIMIT %%limit%%
