PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT *
FROM <http://data.doremus.org/>
FROM <http://data.doremus.org/vocabulary>

WHERE {
    %%uri%% a efrbroo:F22_Self-Contained_Expression ;
             ecrm:P102_has_title ?title .
    OPTIONAL{%%uri%% efrbroo:R45i_was_assigned_by ?assigned .}
	  OPTIONAL{%%uri%% ecrm:P3_has_note ?note .}
    OPTIONAL {
          %%uri%% mus:U13_has_casting ?castingURI .
          ?castingURI mus:U23_has_casting_detail ?castingDet .
          ?castingDet mus:U2_foresees_use_of_medium_of_performance_of_type ?mopURI .
          { ?mopURI ecrm:P1_is_identified_by ?mop }
          UNION
          {
            ?mopURI skos:prefLabel ?mop .
            FILTER regex(lang(?mop), "%%lang%%")
          }
    }
    OPTIONAL{%%uri%% efrbroo:R17i_was_created_by ?created .}
    OPTIONAL{
            %%uri%% mus:U12_has_genre ?genreURI .
            ?genreURI skos:prefLabel ?genre .
            FILTER regex(lang(?genre), "%%lang%%")
    }
    OPTIONAL{%%uri%% mus:U12_has_genre ?genreN .
             ?genreN ecrm:P1_is_identified_by ?genreID .}
    OPTIONAL{%%uri%% efrbroo:R40i_is_representative_expression_of ?repExp .}
    OPTIONAL{
			%%uri%% mus:U17_has_opus_statement ?opus .
			OPTIONAL{?opus ecrm:P3_has_note ?opusNote .}
	  }
    OPTIONAL{%%uri%% mus:U10_has_order_number ?order .}
    OPTIONAL{%%uri%% mus:U11_has_key ?keyURI .
          ?keyURI skos:prefLabel ?key .
          FILTER regex(lang(?key), "%%lang%%")
    }
    OPTIONAL{%%uri%% mus:U11_has_key ?keyN .
             ?keyN ecrm:P1_is_identified_by ?keyID .}
    OPTIONAL{
			%%uri%% ecrm:P67_refers_to ?refers .
			OPTIONAL{?refers ecrm:P3_has_note ?refersNote .}
	  }
    OPTIONAL{
  		%%uri%% mus:U16_has_catalogue_statement ?catalog .
  		?catalog ecrm:P3_has_note ?catalogNote .
	  }
    OPTIONAL{%%uri%% ecrm:P165i_is_incorporated_in ?incorporated .}
    OPTIONAL{%%uri%% ecrm:P1_is_identified_by ?identified .}
    OPTIONAL{?complexWork efrbroo:R40_has_representative_expression %%uri%% .}
    OPTIONAL{?individualWork efrbroo:R9_is_realised_in %%uri%% .}
    OPTIONAL{
      ?expCreation efrbroo:R17_created %%uri%% .
      OPTIONAL {
        ?expCreation ecrm:P9_consists_of ?activity .
        ?activity ecrm:P14_carried_out_by ?person .
        ?person ecrm:P1_is_identified_by ?composer .
      }
      OPTIONAL {
        ?expCreation ecrm:P4_has_time-span ?creationTimeSpan.
        ?creationTimeSpan ecrm:P82_at_some_time_within ?creationTime.
      }
    }
}
