PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT
  ?expression
  sql:BEST_LANGMATCH(?title, '%%lang%%, en;q=0.9, *;q=0.1', 'en') AS ?title
  sql:BEST_LANGMATCH(?composer, '%%lang%%, en;q=0.9, *;q=0.1', 'en') AS ?composer
  (SAMPLE(?catalogue) AS ?catalogue)
WHERE {
    %%uri%% a efrbroo:F22_Self-Contained_Expression .
    ?expCreationOrig efrbroo:R17_created %%uri%% .
    {
      ?expCreationOrig ecrm:P9_consists_of / ecrm:P14_carried_out_by ?personOrig .
    } UNION {
      ?expCreationOrig ecrm:P14_carried_out_by ?personOrig .
    }
    ?personOrig rdfs:label | ecrm:P131_is_identified_by ?composer .

    ?expression a efrbroo:F22_Self-Contained_Expression ;
            mus:U70_has_title | ecrm:P102_has_title ?title .
    OPTIONAL { ?expression mus:U16_has_catalogue_statement / rdfs:label ?catalogue }
    ?expCreation efrbroo:R17_created ?expression .
    {
      ?expCreation ecrm:P9_consists_of / ecrm:P14_carried_out_by ?personOrig .
    } UNION {
      ?expCreation ecrm:P14_carried_out_by ?personOrig .
    }
    FILTER( str(?composer) != 'Radio France')
    FILTER( ?expression != %%uri%%)
    BIND(RAND() as ?rnd)
} ORDER BY ?rnd
 LIMIT %%limit%%
