PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX mus: <http://data.doremus.org/ontology#>

SELECT ?expression (SAMPLE(?title) AS ?title) (SAMPLE(?composer) AS ?composer)
WHERE {
    ?expression a  efrbroo:F22_Self-Contained_Expression ;
            $if{key} mus:U11_has_key <%%key%%>; $end
            $if{genre} mus:U12_has_genre <%%genre%%>; $end
            mus:U70_has_title ?title .
    OPTIONAL{
      ?expCreation efrbroo:R17_created ?expression ;
                  ecrm:P9_consists_of ?activity .
      ?activity ecrm:P14_carried_out_by ?person .
      ?person ecrm:P131_is_identified_by ?composer .
     }
    FILTER (str(?title) != "" $if{title} && regex(str(?title),'%%title%%', 'i') $end )
}
GROUP BY (?expression)
ORDER BY (?expression)
LIMIT %%lim%%
