SELECT ?label ?concept from <http://data.doremus.org/vocabulary/key>
WHERE {
    ?concept a <http://www.w3.org/2004/02/skos/core#Concept> ;
         <http://www.w3.org/2004/02/skos/core#prefLabel> ?label .

    FILTER(lang(?label) = "fr")
}
