PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX mus: <http://data.doremus.org/ontology#>

SELECT ?expressions (SAMPLE(?titleAux) AS ?title) (SAMPLE(?activityAux) AS ?activity) (SAMPLE(?personAux) AS ?person) (SAMPLE(?composerAux) AS ?composer)
FROM <http://data.doremus.org/>
WHERE {
    ?expressions a  efrbroo:F22_Self-Contained_Expression ;
             ecrm:P102_has_title ?titleAux .
    OPTIONAL{?expCreation efrbroo:R17_created ?expressions ;
            ecrm:P9_consists_of ?activityAux .
            ?activityAux ecrm:P14_carried_out_by ?personAux .
            ?personAux ecrm:P1_is_identified_by ?composerAux .
     }
    FILTER (str(?titleAux) != "")
}
GROUP BY (?expressions)
ORDER BY (?expressions)
LIMIT %%lim%%
