PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX cidoc: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX frbroo: <http://erlangen-crm.org/efrbroo/>

SELECT DISTINCT *
WHERE {
    $$uri$$ skos:prefLabel ?name .
    FILTER (lang(?name) = "$$lang$$")
}
