PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT
  ?uri
  sql:BEST_LANGMATCH(?prefLabel, '%%lang%%, en;q=0.9, en-gb;q=0.8, *;q=0.1', 'en') as ?label
WHERE {
    ?something %%prop%% ?uri .
    ?uri skos:prefLabel ?prefLabel
}
GROUP BY ?uri ?prefLabel
ORDER BY (COUNT(?something))
