SELECT DISTINCT
  ?uri
  sql:BEST_LANGMATCH(?label, '%%lang%%', 'en') AS ?label
  ?names
  ?birth
  ?death
  ?birthPlace
  ?deathPlace
  ?pic
  ?comment
  ?sameAs
  ?wikipedia

WHERE {
  ?uri a ecrm:E21_Person ;
         rdfs:label | foaf:name ?label ;
         foaf:name ?names .
  OPTIONAL { ?uri schema:birthDate ?birth }
  OPTIONAL { ?uri schema:deathDate ?death }
  OPTIONAL { ?uri dbpprop:birthPlace ?birthPlace }
  OPTIONAL { ?uri dbpprop:deathPlace ?deathPlace }
  OPTIONAL { ?uri foaf:depiction ?pic }
  OPTIONAL { ?uri rdfs:comment ?comment }
  OPTIONAL { ?uri owl:sameAs ?sameAs }
  OPTIONAL { ?uri foaf:isPrimaryTopicOf ?wikipedia }

  VALUES ?uri { %%uri%% }
}
