SELECT DISTINCT ?date, ?artist, ?role, ?roleLabel, ?event, ?expression, ?classExpr, ?title, ?pic, ?source
WHERE {
  VALUES ?artist { %%uri%% }
  OPTIONAL { ?artist foaf:depiction ?pic }

  ?activity ecrm:P14_carried_out_by ?artist.
  OPTIONAL {
    ?activity mus:U31_had_function | mus:U35_foresees_function | mus:U1_used_medium_of_performance ?role .
    { SELECT ?role sql:BEST_LANGMATCH(?roleLabel, '%%lang%%, en;q=0.9, *;q=0.1', 'en') as ?roleLabel
      WHERE { ?role skos:prefLabel ?roleLabel }}
  }

  ?event ecrm:P9_consists_of ?activity ;
     efrbroo:R17_created ?expression .
  OPTIONAL { ?event ecrm:P4_has_time-span / time:hasBeginning / time:inXSDDate ?date }

  ?expression a ?classExpr;
    prov:wasDerivedFrom / prov:wasAttributedTo ?source.

  { SELECT ?expression sql:BEST_LANGMATCH(?title, '%%lang%%, en;q=0.9, *;q=0.1', 'en') as ?title
    WHERE { ?expression rdfs:label|ecrm:P102_has_title ?title . }
  }
}
